In [417]:
import pandas as pd
import numpy as np

df1 = pd.read_csv("Movies with Plots.csv")
df2 = pd.read_csv("ratings.csv")

In [418]:
df1.head()

Unnamed: 0  movieId                               title  \
0           0        1                    Toy Story (1995)   
1           1        2                      Jumanji (1995)   
2           2        3             Grumpier Old Men (1995)   
3           3        4            Waiting to Exhale (1995)   
4           4        5  Father of the Bride Part II (1995)   

                                        genres                   movie_name  \
0  Adventure|Animation|Children|Comedy|Fantasy                    Toy Story   
1                   Adventure|Children|Fantasy                      Jumanji   
2                               Comedy|Romance             Grumpier Old Men   
3                         Comedy|Drama|Romance            Waiting to Exhale   
4                                       Comedy  Father of the Bride Part II   

                                                Plot  
0  A little boy named Andy loves to be in his roo...  
1  Jumanji, one of the most unique--and dangerous...  
2  Things don't seem to change much in Wabasha Co...  
3  This story based on the best selling novel by ...  
4  In this sequel to "Father of the Bride", Georg...

In [419]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  9742 non-null   int64 
 1   movieId     9742 non-null   int64 
 2   title       9742 non-null   object
 3   genres      9742 non-null   object
 4   movie_name  9742 non-null   object
 5   Plot        7855 non-null   object
dtypes: int64(2), object(4)
memory usage: 456.8+ KB


In [420]:
df1.drop(columns='Unnamed: 0')

movieId                                      title  \
0           1                           Toy Story (1995)   
1           2                             Jumanji (1995)   
2           3                    Grumpier Old Men (1995)   
3           4                   Waiting to Exhale (1995)   
4           5         Father of the Bride Part II (1995)   
...       ...                                        ...   
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                                           genres  \
0     Adventure|Animation|Children|Comedy|Fantasy   
1                      Adventure|Children|Fantasy   
2                                  Comedy|Romance   
3                            Comedy|Drama|Romance   
4                                          Comedy   
...                                           ...   
9737              Action|Animation|Comedy|Fantasy   
9738                     Animation|Comedy|Fantasy   
9739                                        Drama   
9740                             Action|Animation   
9741                                       Comedy   

                              movie_name  \
0                              Toy Story   
1                                Jumanji   
2                       Grumpier Old Men   
3                      Waiting to Exhale   
4            Father of the Bride Part II   
...                                  ...   
9737  Black Butler: Book of the Atlantic   
9738               No Game No Life: Zero   
9739                               Flint   
9740        Bungo Stray Dogs: Dead Apple   
9741        Andrew Dice Clay: Dice Rules   

                                                   Plot  
0     A little boy named Andy loves to be in his roo...  
1     Jumanji, one of the most unique--and dangerous...  
2     Things don't seem to change much in Wabasha Co...  
3     This story based on the best selling novel by ...  
4     In this sequel to "Father of the Bride", Georg...  
...                                                 ...  
9737  Whispers turn into screaming headlines in Earl...  
9738  The Movie following the light novel series by ...  
9739  A woman deals with the toxic water scandal in ...  
9740  Rivalry between groups of criminals and detect...  
9741                                                NaN  

[9742 rows x 5 columns]

In [421]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   userId     100836 non-null  int64  
 1   movieId    100836 non-null  int64  
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 3.1 MB


In [422]:
df = pd.merge(df1, df2, on='movieId', how='right')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100836 entries, 0 to 100835
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Unnamed: 0  100836 non-null  int64  
 1   movieId     100836 non-null  int64  
 2   title       100836 non-null  object 
 3   genres      100836 non-null  object 
 4   movie_name  100836 non-null  object 
 5   Plot        83447 non-null   object 
 6   userId      100836 non-null  int64  
 7   rating      100836 non-null  float64
 8   timestamp   100836 non-null  int64  
dtypes: float64(1), int64(4), object(4)
memory usage: 7.7+ MB


In [423]:
df.drop(columns={'Unnamed: 0', 'timestamp'})

movieId                           title  \
0             1                Toy Story (1995)   
1             3         Grumpier Old Men (1995)   
2             6                     Heat (1995)   
3            47     Seven (a.k.a. Se7en) (1995)   
4            50      Usual Suspects, The (1995)   
...         ...                             ...   
100831   166534                    Split (2017)   
100832   168248   John Wick: Chapter Two (2017)   
100833   168250                  Get Out (2017)   
100834   168252                    Logan (2017)   
100835   170875  The Fate of the Furious (2017)   

                                             genres               movie_name  \
0       Adventure|Animation|Children|Comedy|Fantasy                Toy Story   
1                                    Comedy|Romance         Grumpier Old Men   
2                             Action|Crime|Thriller                     Heat   
3                                  Mystery|Thriller                    Seven   
4                            Crime|Mystery|Thriller      Usual Suspects, The   
...                                             ...                      ...   
100831                        Drama|Horror|Thriller                    Split   
100832                        Action|Crime|Thriller   John Wick: Chapter Two   
100833                                       Horror                  Get Out   
100834                                Action|Sci-Fi                    Logan   
100835                  Action|Crime|Drama|Thriller  The Fate of the Furious   

                                                     Plot  userId  rating  
0       A little boy named Andy loves to be in his roo...       1     4.0  
1       Things don't seem to change much in Wabasha Co...       1     4.0  
2       Hunters and their prey--Neil and his professio...       1     4.0  
3       A veteran samurai, who has fallen on hard time...       1     5.0  
4                                                     NaN       1     5.0  
...                                                   ...     ...     ...  
100831  Though Kevin (James McAvoy) has evidenced 23 p...     610     4.0  
100832                                                NaN     610     5.0  
100833  Chris and his girlfriend Rose go upstate to vi...     610     5.0  
100834  In 2029 the mutant population has shrunken sig...     610     5.0  
100835  Now that Dominic Toretto (Vin Diesel) and Lett...     610     3.0  

[100836 rows x 7 columns]

In [424]:
df.dropna(subset=['Plot'], inplace=True)

In [425]:
df.drop(['Unnamed: 0', 'timestamp'], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83447 entries, 0 to 100835
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   movieId     83447 non-null  int64  
 1   title       83447 non-null  object 
 2   genres      83447 non-null  object 
 3   movie_name  83447 non-null  object 
 4   Plot        83447 non-null  object 
 5   userId      83447 non-null  int64  
 6   rating      83447 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 5.1+ MB


In [426]:
df.head()

movieId                        title  \
0        1             Toy Story (1995)   
1        3      Grumpier Old Men (1995)   
2        6                  Heat (1995)   
3       47  Seven (a.k.a. Se7en) (1995)   
5       70   From Dusk Till Dawn (1996)   

                                        genres           movie_name  \
0  Adventure|Animation|Children|Comedy|Fantasy            Toy Story   
1                               Comedy|Romance     Grumpier Old Men   
2                        Action|Crime|Thriller                 Heat   
3                             Mystery|Thriller                Seven   
5                Action|Comedy|Horror|Thriller  From Dusk Till Dawn   

                                                Plot  userId  rating  
0  A little boy named Andy loves to be in his roo...       1     4.0  
1  Things don't seem to change much in Wabasha Co...       1     4.0  
2  Hunters and their prey--Neil and his professio...       1     4.0  
3  A veteran samurai, who has fallen on hard time...       1     5.0  
5  After a bank heist in Abilene with several cas...       1     3.0

In [427]:
df.to_csv('Movies dataset_v1.1.csv', index=False)

In [428]:
new_df = pd.read_csv('Movies dataset_v1.1.csv')
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83447 entries, 0 to 83446
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   movieId     83447 non-null  int64  
 1   title       83447 non-null  object 
 2   genres      83447 non-null  object 
 3   movie_name  83447 non-null  object 
 4   Plot        83447 non-null  object 
 5   userId      83447 non-null  int64  
 6   rating      83447 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 4.5+ MB


In [429]:
new_df.isnull().sum()

movieId       0
title         0
genres        0
movie_name    0
Plot          0
userId        0
rating        0
dtype: int64

In [430]:
# Creating a pivot table with userId as rows, movieId as columns, and rating as values
svd_input_matrix = new_df.pivot_table(
    index='userId', columns='movieId', values='rating', fill_value=0)

# Printing the input matrix
print(svd_input_matrix)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0       0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     0.0     0.0     0.0     0.0     0.0     2.5       0   
607         4.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
608         2.5     2.0     2.0     0.0     0.0     0.0     0.0       0   
609         3.0     0.0     0.0     0.0     0.0     0.0     0.0       0   
610         5.0     0.0     0.0     0.0     0.0     5.0     0.0       0   

movieId  9       10     

In [431]:
#This code block is to verify if the values are present properly in the matrix

# Access the first row of svd_input_matrix
first_row = svd_input_matrix.iloc[0]

# Find the number of unique values in the first row
print(np.count_nonzero(first_row))

192


In [432]:
# taking 20 movie ratings from user
user_ratings = {
    228888: 4.0,
    1196: 4.5,
    172288885: 4.0,
    260: 5.0,
    356: 5.5,
    592: 4.5,
    648: 4.0,
    1089: 3.0
}

In [433]:
import numpy as np
import pandas as pd
from scipy.sparse.linalg import svds

# create the matrix
ratings = np.array(svd_input_matrix)

# calculate the SVD
U, sigma, Vt = svds(ratings, k=len(user_ratings))

# transform sigma into a diagonal matrix
sigma = np.diag(sigma)

# calculate the predicted ratings
predicted_ratings = np.dot(np.dot(U, sigma), Vt)

# create a dataframe of predicted ratings with row names and column names
movie_names = svd_input_matrix.columns
user_ids = svd_input_matrix.index
predicted_ratings_df = pd.DataFrame(predicted_ratings, index=user_ids, columns=movie_names)

# print the predicted ratings dataframe
print(predicted_ratings_df)


movieId    1         2         3         4         5         6         7       \
userId                                                                          
1        2.927076  1.038270  0.788886 -0.026526  0.119842  1.826674  0.133547   
2        0.112900  0.038320 -0.113751 -0.004498 -0.032041  0.121144 -0.048753   
3        0.039082  0.014085  0.027300 -0.003444 -0.008968  0.059804 -0.009452   
4        1.637111  0.365188  0.159709  0.059278  0.172498  0.413910  0.309884   
5        1.320766  1.026573  0.445179  0.132571  0.573720  0.767041  0.655450   
...           ...       ...       ...       ...       ...       ...       ...   
606      3.419544  0.747020  0.186633  0.172609  0.712238  0.596123  1.349009   
607      2.456025  1.029067  0.660517  0.028241  0.295353  1.566373  0.369613   
608      2.654924  1.970892  1.846728 -0.081660  0.511665  3.139343  0.505620   
609      0.820714  0.638531  0.296854  0.079454  0.336219  0.677016  0.384666   
610      1.134173  2.352142 

In [434]:
from os import error
import numpy as np
import pandas as pd
from scipy.spatial.distance import cosine
import warnings
warnings.filterwarnings("ignore")

# converting user ratings to a dataframe
user_ratings_df = pd.DataFrame.from_dict(user_ratings, orient='index', columns=['rating'])

# creating a new row for the user in the predicted ratings dataframe
user_ratings_df = user_ratings_df.T.reindex(columns=predicted_ratings_df.columns, fill_value=0)

# appending the user's ratings to the predicted ratings dataframe
predicted_ratings_df = predicted_ratings_df.append(user_ratings_df, ignore_index=True)

# calculate the cosine similarity between the user and all other users
similarities = pd.DataFrame(columns=['userId', 'similarity'])
for index, row in predicted_ratings_df.iterrows():
    if index != predicted_ratings_df.index[-1]:  # exclude the user's own row
        similarity = 1 - cosine(predicted_ratings_df.loc[predicted_ratings_df.index[-1]], row)
        similarities = similarities.append({'userId': index, 'similarity': similarity}, ignore_index=True)

# finding the most similar user
most_similar_user = similarities.loc[similarities['similarity'].idxmax()]['userId']

# geting the top 30 movies rated by the most similar user
top_movies = predicted_ratings_df.loc[most_similar_user].sort_values(ascending=False)

#removing the movies already rated by the user from the most_similar_user row
top_movies = top_movies.drop(list(user_ratings.keys()), errors='ignore')

# printing the top 30 movies and their predicted evaluation metrics from SVD
print(top_movies)

movieId
296     2.927087
110     2.573298
2571    2.418450
589     2.233135
527     2.194135
          ...   
3882   -0.240468
4890   -0.252860
7451   -0.258916
3489   -0.262736
6936   -0.304394
Name: 71, Length: 7836, dtype: float64


In [435]:
top_movies_df = pd.DataFrame(top_movies.reset_index())
top_movies_df.columns = ['movieId', 'predicted_evaluation']

print(top_movies_df)

      movieId  predicted_evaluation
0         296              2.927087
1         110              2.573298
2        2571              2.418450
3         589              2.233135
4         527              2.194135
...       ...                   ...
7831     3882             -0.240468
7832     4890             -0.252860
7833     7451             -0.258916
7834     3489             -0.262736
7835     6936             -0.304394

[7836 rows x 2 columns]


# **Corresponding movie_names of the movieId's in user_ratings dictionary**

In [436]:
movie_names = list(new_df['movie_name'])
for key in user_ratings:
    if key not in new_df['movieId'].unique():
        user_ratings[key] = "Not present"
    else:
        user_ratings[key] = movie_names[new_df.loc[new_df['movieId'] == key].index[0]]

user_input_movies_df=pd.DataFrame.from_dict(user_ratings, orient='index', columns=['movie_name'])
user_input_movies_df = user_input_movies_df[user_input_movies_df['movie_name'] != 'Not present']

print(user_input_movies_df)
print(user_input_movies_df.columns)

                                          movie_name
1196  Star Wars: Episode V - The Empire Strikes Back
260               Star Wars: Episode IV - A New Hope
356                                     Forrest Gump
592                                           Batman
648                              Mission: Impossible
1089                                  Reservoir Dogs
Index(['movie_name'], dtype='object')


In [437]:
# Left join the user_input_movies_df with the new_df on movie_name column
usermoviewithplot = user_input_movies_df.merge(new_df, on='movie_name', how='left')
usermoviewithplot = usermoviewithplot[['movie_name', 'Plot']].drop_duplicates()

# Display the merged dataframe
print(usermoviewithplot)
print(usermoviewithplot.columns)

                                          movie_name  \
0     Star Wars: Episode V - The Empire Strikes Back   
211               Star Wars: Episode IV - A New Hope   
462                                     Forrest Gump   
791                                           Batman   
985                              Mission: Impossible   
1147                                  Reservoir Dogs   

                                                   Plot  
0     Luke Skywalker, Han Solo, Princess Leia and Ch...  
211   The Imperial Forces, under orders from cruel D...  
462   Forrest Gump is a simple man with a low I.Q. b...  
791   Gotham City. Crime boss Carl Grissom (Jack Pal...  
985   In the fourth installment of the Mission Impos...  
1147  Six thugs, who are strangers to each other, ar...  
Index(['movie_name', 'Plot'], dtype='object')


In [438]:
#Finding out the userId of the most similar user in our user-item matrix
print(most_similar_user)

# Create a dictionary to map movieId to movie_name
movie_dict = dict(zip(new_df['movieId'], new_df['movie_name']))

# Replace the movieId with its corresponding movie_name value
top_movies_df['movieId'] = top_movies.index.map(movie_dict)

71.0


In [439]:
# create a dictionary mapping movie names to genres
movie_genres = dict(new_df[['movie_name', 'genres']].drop_duplicates().values)

# add a new 'genres' column to the top_movies dataframe
top_movies_df['genres'] = top_movies_df['movieId'].map(movie_genres)

# **Top 25 movies with their evaluation metrics and genres**

In [440]:
top_movies_df.columns = ['movie_name', 'predicted_evaluation', 'genres']

print(top_movies_df[:25])

                                    movie_name  predicted_evaluation  \
0                                 Pulp Fiction              2.927087   
1                                   Braveheart              2.573298   
2                                  Matrix, The              2.418450   
3                   Terminator 2: Judgment Day              2.233135   
4                             Schindler's List              2.194135   
5                                Jurassic Park              1.998063   
6                                    Apollo 13              1.918491   
7                                Fugitive, The              1.909206   
8                          Saving Private Ryan              1.898986   
9                                        Seven              1.827194   
10                                  Fight Club              1.660862   
11                              Godfather, The              1.656720   
12  Star Wars: Episode VI - Return of the Jedi              1.61

In [441]:
top_movies_df.columns

Index(['movie_name', 'predicted_evaluation', 'genres'], dtype='object')

In [442]:
# Ask the user for their preferred and disliked genres
preferred_genres = input("Enter your 3 most liked genres, separated by commas: ").split("|")
disliked_genres = input("Enter your 3 most disliked genres, separated by commas: ").split("|")

# Filter out movies that the user dislikes
disliked_movies = top_movies_df[top_movies_df['genres'].apply(lambda x: any(genre in disliked_genres for genre in x.split("|")))]

# Remove movies present in disliked movies from top_movies_df
top_movies_df = top_movies_df[~top_movies_df['movie_name'].isin(disliked_movies['movie_name'])]

# Filter out movies that don't match the user's preferred genres
preferred_movies = top_movies_df[top_movies_df['genres'].apply(lambda x: any(genre in preferred_genres for genre in x.split("|")))]


Enter your 3 most liked genres, separated by commas: Action|Sci-Fi|Adventure
Enter your 3 most disliked genres, separated by commas: Thriller|Fantasy|Children


In [443]:
# Include movies in preferred_movies in top_movies_df
top_movies_df = pd.concat([top_movies_df, preferred_movies])

# Multiply the predicted_evaluation of movies in preferred_movies by 2
preferred_movies['predicted_evaluation'] = preferred_movies['predicted_evaluation'] * 2

top_movies_df = top_movies_df.sort_values('predicted_evaluation', ascending=False)
top_movies_df = top_movies_df.drop_duplicates(subset='movie_name', keep='first')

In [444]:
top_movies_df=top_movies_df[:25]
print(top_movies_df[:25])

                                    movie_name  predicted_evaluation  \
1                                   Braveheart              2.573298   
3                   Terminator 2: Judgment Day              2.233135   
4                             Schindler's List              2.194135   
6                                    Apollo 13              1.918491   
7                                Fugitive, The              1.909206   
8                          Saving Private Ryan              1.898986   
11                              Godfather, The              1.656720   
12  Star Wars: Episode VI - Return of the Jedi              1.614812   
13                          Dances with Wolves              1.575997   
14                     Raiders of the Lost Ark              1.556280   
20                             American Beauty              1.397024   
21                            Sixth Sense, The              1.306959   
23                                   Gladiator              1.29

In [445]:
# create a dictionary mapping movie names to genres
movie_plot = dict(new_df[['movie_name', 'Plot']].drop_duplicates().values)

# add a new 'genres' column to the top_movies dataframe
top_movies_df['Plot'] = top_movies_df['movie_name'].map(movie_plot)

In [446]:
top_movies_df

movie_name  predicted_evaluation  \
1                                   Braveheart              2.573298   
3                   Terminator 2: Judgment Day              2.233135   
4                             Schindler's List              2.194135   
6                                    Apollo 13              1.918491   
7                                Fugitive, The              1.909206   
8                          Saving Private Ryan              1.898986   
11                              Godfather, The              1.656720   
12  Star Wars: Episode VI - Return of the Jedi              1.614812   
13                          Dances with Wolves              1.575997   
14                     Raiders of the Lost Ark              1.556280   
20                             American Beauty              1.397024   
21                            Sixth Sense, The              1.306959   
23                                   Gladiator              1.296406   
28                          Back to the Future              1.144498   
29          Indiana Jones and the Last Crusade              1.096133   
30                                       Alien              1.063567   
31                                      Aliens              1.061218   
33                          American History X              1.040666   
34                                    Stargate              1.034503   
38                                  Goodfellas              1.006211   
42                           Good Will Hunting              0.978087   
43                            Dark Knight, The              0.954547   
45             One Flew Over the Cuckoo's Nest              0.950383   
47                                Men in Black              0.921084   
51                      Star Trek: Generations              0.843606   

                            genres  \
1                 Action|Drama|War   
3                    Action|Sci-Fi   
4                        Drama|War   
6             Adventure|Drama|IMAX   
7                            Drama   
8                 Action|Drama|War   
11                     Crime|Drama   
12         Action|Adventure|Sci-Fi   
13         Adventure|Drama|Western   
14                Action|Adventure   
20                   Drama|Romance   
21            Drama|Horror|Mystery   
23                    Action|Drama   
28         Adventure|Comedy|Sci-Fi   
29                Action|Adventure   
30                   Horror|Sci-Fi   
31  Action|Adventure|Horror|Sci-Fi   
33                     Crime|Drama   
34         Action|Adventure|Sci-Fi   
38                     Crime|Drama   
42                   Drama|Romance   
43         Action|Crime|Drama|IMAX   
45                           Drama   
47            Action|Comedy|Sci-Fi   
51          Adventure|Drama|Sci-Fi   

                                                 Plot  
1   William Wallace is a Scottish rebel who leads ...  
3   Over 10 years have passed since the first mach...  
4   Oskar Schindler is a vain and greedy German bu...  
6   Based on the true story of the ill-fated 13th ...  
7   It chronicles the rise of Carlos Ghosn as well...  
8   Opening with the Allied invasion of Normandy o...  
11  A thriller focusing on the rise of a group of ...  
12  Luke Skywalker battles Jabba the Hutt and Dart...  
13  Lt. John Dunbar is dubbed a hero after he acci...  
14  The year is 1936. An archeology professor name...  
20  After his death sometime in his 43rd year, sub...  
21  A brief feature that showcases various cast me...  
23  Maximus is a powerful Roman general, loved by ...  
28  Marty McFly, a typical American teenager of th...  
29  An art collector appeals to Indiana Jones to e...  
30  In the distant future, the crew of the commerc...  
31  57 years after Ellen Ripley had a close encoun...  
33  Derek Vineyard is paroled after serving 3 year...  
34  In 1928, in Egypt, a strange device is found b...  
38  Henry Hill might be a small time gangster, who... 

In [447]:
import pandas as pd
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import re

nltk.download('punkt')

# Define a function for preprocessing
def preprocess(text):
    # Remove special characters and digits
    text = re.sub(r'\W+', ' ', text)
    text = re.sub(r'\d+', '', text)
    # Tokenize the text
    tokens = word_tokenize(text)
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word.lower() for word in tokens if word.lower() not in stop_words]
    # Stem the words
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]
    # Join the tokens back into a string
    text = ' '.join(tokens)
    return text

# Apply the preprocessing function to the 'Plot' column
usermoviewithplot['Plot'] = usermoviewithplot['Plot'].apply(preprocess)

top_movies_df['Plot'] = top_movies_df['Plot'].apply(preprocess)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [448]:
# Print the preprocessed dataframe
print(usermoviewithplot['Plot'])

print(top_movies_df['Plot'])

0       luke skywalk han solo princess leia chewbacca ...
211     imperi forc order cruel darth vader hold princ...
462     forrest gump simpl man low q good intent run c...
791     gotham citi crime boss carl grissom jack palan...
985     fourth instal mission imposs seri ethan hunt n...
1147    six thug stranger hire crime boss joe cabot ca...
Name: Plot, dtype: object
1     william wallac scottish rebel lead upris cruel...
3     year pass sinc first machin call termin tri ki...
4     oskar schindler vain greedi german businessman...
6     base true stori ill fate th apollo mission bou...
7     chronicl rise carlo ghosn well intern rivalri ...
8     open alli invas normandi june member nd ranger...
11    thriller focus rise group influenti power gang...
12    luke skywalk battl jabba hutt darth vader save...
13    lt john dunbar dub hero accident lead union tr...
14    year archeolog professor name indiana jone ven...
20    death sometim rd year suburbanit lester burnha...
21    brie

In [449]:
# usermoviewithplot["Plot"]=usermoviewithplot["Plot"].apply(lambda x : " ".join([i for i in x]))
usermoviewithplot["Plot"]

0       luke skywalk han solo princess leia chewbacca ...
211     imperi forc order cruel darth vader hold princ...
462     forrest gump simpl man low q good intent run c...
791     gotham citi crime boss carl grissom jack palan...
985     fourth instal mission imposs seri ethan hunt n...
1147    six thug stranger hire crime boss joe cabot ca...
Name: Plot, dtype: object

In [450]:
top_movies_df['Plot']

1     william wallac scottish rebel lead upris cruel...
3     year pass sinc first machin call termin tri ki...
4     oskar schindler vain greedi german businessman...
6     base true stori ill fate th apollo mission bou...
7     chronicl rise carlo ghosn well intern rivalri ...
8     open alli invas normandi june member nd ranger...
11    thriller focus rise group influenti power gang...
12    luke skywalk battl jabba hutt darth vader save...
13    lt john dunbar dub hero accident lead union tr...
14    year archeolog professor name indiana jone ven...
20    death sometim rd year suburbanit lester burnha...
21    brief featur showcas variou cast member discus...
23    maximu power roman gener love peopl age empero...
28    marti mcfli typic american teenag eighti accid...
29    art collector appeal indiana jone embark searc...
30    distant futur crew commerci spaceship nostromo...
31    year ellen ripley close encount reptilian alie...
33    derek vineyard parol serv year prison brut

In [451]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Create TF-IDF vectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the plot column in dataset1
tfidf_matrix1 = vectorizer.fit_transform(usermoviewithplot["Plot"])

# Transform the plot column in dataset2 using the same vectorizer
tfidf_matrix2 = vectorizer.transform(top_movies_df['Plot'])

# Compute the cosine similarity between each row in tfidf_matrix1 and tfidf_matrix2
similarity_matrix = cosine_similarity(tfidf_matrix2, tfidf_matrix1)


In [452]:
vectorizer.get_feature_names_out()

array(['access', 'action', 'allianc', 'along', 'although', 'amongst',
       'anyon', 'appar', 'armi', 'articl', 'assembl', 'attack', 'attempt',
       'backup', 'basing', 'batman', 'beauti', 'beckon', 'begin', 'best',
       'billionair', 'bomb', 'boss', 'bruce', 'brutal', 'bubba', 'bumper',
       'cabot', 'call', 'captain', 'carl', 'carri', 'caus', 'chase',
       'chemic', 'chewbacca', 'childhood', 'choos', 'citi', 'civilian',
       'close', 'code', 'companion', 'complet', 'concentr', 'cop',
       'craze', 'creat', 'crime', 'cruel', 'curran', 'dagobah', 'damag',
       'dan', 'danger', 'dark', 'darth', 'death', 'destini', 'diamond',
       'disast', 'disavow', 'donat', 'droid', 'dubai', 'duel', 'duo',
       'effect', 'effort', 'empir', 'end', 'entir', 'escap', 'ethan',
       'everyday', 'explos', 'face', 'falcon', 'fall', 'fals', 'famou',
       'fighter', 'find', 'fish', 'fleet', 'forc', 'form', 'forrest',
       'fourth', 'freedom', 'friend', 'gain', 'galact', 'galaxi', 'get'

In [453]:
print(similarity_matrix)

[[0.         0.10787587 0.03370469 0.03063065 0.         0.16168575]
 [0.03423752 0.         0.12464716 0.06580542 0.08092146 0.10847687]
 [0.         0.         0.06153607 0.05592366 0.         0.07379911]
 [0.         0.         0.         0.         0.07763763 0.09038508]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.07286644 0.0307618  0.1356144  0.16468827]
 [0.         0.         0.1648633  0.         0.0620612  0.15553431]
 [0.43679793 0.5079229  0.0263355  0.         0.08138787 0.        ]
 [0.         0.         0.26998661 0.12294548 0.         0.05431377]
 [0.09349046 0.09984901 0.08337103 0.04741567 0.         0.0748275 ]
 [0.02301505 0.         0.34024514 0.08129847 0.00758378 0.07368275]
 [0.         0.         0.         0.         0.         0.12782381]
 [0.         0.         0.17493302 0.10598547 0.         0.06993135]
 [0.         0.         0.12963372 0.07963951 0.04326771 0.10291966]
 [0.13411072 0.         0.07484319

In [454]:
import numpy as np

# your matrix
m = np.array(similarity_matrix)

# sum the rows
row_sums = m.sum(axis=1)

# print the row sums
row_sums=(row_sums/len(user_input_movies_df))
print(row_sums)

[0.05564949 0.06901474 0.03187647 0.02800379 0.         0.06732182
 0.06374313 0.17540737 0.07454097 0.06649228 0.08763753 0.02130397
 0.05847497 0.05924343 0.04394142 0.04847642 0.07295539 0.06531293
 0.07723378 0.08668617 0.04327801 0.04843131 0.04234553 0.08519
 0.10232603]


In [455]:
top_movies_df["Similarity"]=row_sums

In [456]:
print(f"Disliked Genres: {disliked_genres}")
print(f"Preferred Genres: {preferred_genres}")

Disliked Genres: ['Thriller', 'Fantasy', 'Children']
Preferred Genres: ['Action', 'Sci-Fi', 'Adventure']


In [457]:
top_movies_df = top_movies_df.sort_values('Similarity', ascending=False)
top_movies_df = top_movies_df[:10]
recommendation = top_movies_df.loc[:, ['movie_name', 'Similarity', 'predicted_evaluation', 'genres']]
print(recommendation)

                                    movie_name  Similarity  \
12  Star Wars: Episode VI - Return of the Jedi    0.175407   
51                      Star Trek: Generations    0.102326   
20                             American Beauty    0.087638   
38                                  Goodfellas    0.086686   
47                                Men in Black    0.085190   
34                                    Stargate    0.077234   
13                          Dances with Wolves    0.074541   
31                                      Aliens    0.072955   
3                   Terminator 2: Judgment Day    0.069015   
8                          Saving Private Ryan    0.067322   

    predicted_evaluation                          genres  
12              1.614812         Action|Adventure|Sci-Fi  
51              0.843606          Adventure|Drama|Sci-Fi  
20              1.397024                   Drama|Romance  
38              1.006211                     Crime|Drama  
47              0.9210